### ISSUE TITLE
AssertionError in dexlib

### ISSUE THREAD

**Issue by xurubin** [brazdil/dexter#1]
Quite a few unit tests (009-instanceof2.apk) throw assertion errors:
java.lang.AssertionError
at org.jf.dexlib.ClassDefItem.internClassDefItem(ClassDefItem.java:118)
at uk.ac.cam.db538.dexter.dex.DexClass.writeToFile(DexClass.java:230)

**Comment by brazdil** [comment]
Fixed in 1777c0c
