### ISSUE TITLE
Control flow  graph building failure

### ISSUE THREAD

**Issue by xurubin** [brazdil/dexter#2]
Unit test of exception.apk:

java.util.NoSuchElementException: Element of InstructionList not found
    at uk.ac.cam.db538.dexter.dex.code.InstructionList.getIndex(InstructionList.java:122)
    at uk.ac.cam.db538.dexter.dex.code.InstructionList.isBetween(InstructionList.java:133)
    at uk.ac.cam.db538.dexter.dex.code.insn.DexInstruction.getSurroundingTryBlock(DexInstruction.java:105)
    at uk.ac.cam.db538.dexter.dex.code.insn.DexInstruction.cfgGetExceptionSuccessors(DexInstruction.java:95)
    at uk.ac.cam.db538.dexter.dex.code.insn.DexInstruction.cfgGetSuccessors(DexInstruction.java:66)
    at uk.ac.cam.db538.dexter.analysis.cfg.ControlFlowGraph.generateCFG(ControlFlowGraph.java:86)
    at uk.ac.cam.db538.dexter.analysis.cfg.ControlFlowGraph.<init>(ControlFlowGraph.java:28)
    at com.rx201.dx.translator.DexCodeAnalyzer.buildInstructionList(DexCodeAnalyzer.java:205)
    at com.rx201.dx.translator.DexCodeAnalyzer.<init>(DexCodeAnalyzer.java:55)
    at com.rx201.dx.translator.DexCodeGeneration.<init>(DexCodeGeneration.java:92)
    at uk.ac.cam.db538.dexter.dex.method.DexMethod.writeToFile(DexMethod.java:107)
    at uk.ac.cam.db538.dexter.dex.DexClass.writeToFile(DexClass.java:220)
    at uk.ac.cam.db538.dexter.dex.Dex.writeToFile(Dex.java:131)
    at com.rx201.dx.translator.test.TranslationTest.test(TranslationTest.java:95)

**Comment by brazdil** [comment]
Fixed in 7707996
